config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'
  get 'public_recipes', to: 'home#public_recipes'
  get 'shopping_list', to: 'home#shopping_list'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :foods, except: :update

  resources :recipes, except: :update do
    resources :recipe_foods, only: %i[create destroy edit new update]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id', dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true, length: { maximum: 200 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @recipes = Recipe.includes([:user]).where(user: current_user)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.includes([:food]).includes([:recipe]).where(recipe_id: params[:id])
  end

  def destroy
    @recipes = Recipe.find(params[:id])

    @recipes.destroy
    redirect_to recipes_path
  end

  def create
    if @recipe.save
      flash[:notice] = 'Recipe saved successfully'
    else
      flash[:alert] = 'Recipe not saved'
    end
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :cooking_time, :preparation_time, :public)
      .merge({ user_id: current_user.id })
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class="new-recipe">
  <%= link_to "Create new recipe", "/recipes/new" %>
</div>
<div class="recipes-container">
  <%@recipes.each do |recipe|%>
    <div class="recipe-container">
      <div class="title-container">
        <h2>
          <%=link_to recipe_path(recipe.id), :class => 'title-anchor' do%><%= recipe.name%><%end%>
        </h2>
        <% if can? :destroy, recipe %>
          <%= button_to 'Remove', recipe_path(recipe.id), method: :delete, class: "delete-btn" %>
        <% end %>
      </div>
      <div class="description-container">
        <p><%= recipe.description %></p>
      </div>
    </div>
  <%end%>
  <p></p>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1> 
<%= form_with url: "/recipes", method: :post, scope: :recipe, class:"form-body" do |form| %>
  <div class="field">
    <%= form.label :Name%> <br>
    <%= form.text_field :name%>
  </div>
  <div class="field">
    <%= form.label :Preparation_time%> <br>
    <%= form.text_field :preparation_time%>
  </div>
  <div class="field">
    <%= form.label :Cooking_time%> <br>
    <%= form.text_field :cooking_time%>
  </div>
  <div class="field">
    <%= form.label :Description%> <br>
    <%= form.text_area :description%>
  </div>
  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public %> 
  </div>
  <div class="actions"><%= form.submit %></div>
<%end%>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<div class="column col-center width-60 gap-1">
  <div class="row row-justify">
    <div class="column">
      <h2>Preparation Time: <%= @recipe.preparation_time %></h2>
      <h2>Cooking Time: <%= @recipe.cooking_time %></h2>
    </div>
    <div>
      <h3>Public<h3>
      <label class="switch">
        <input type="checkbox" <% if @recipe.public %>checked<% end %> disabled>
        <span class="slider round"></span>
      </label>
    </div>
  </div>
  <p><%= @recipe.description %></p>
  <div class="row row-justify">
    <%=link_to shopping_list_path, :class => 'btn' do%>
      <h4>Generate shopping list</h4>
    <%end%>
    <% if can? :create, @recipe %>
      <%= link_to new_recipe_recipe_food_path(@recipe.id), class: "btn" do %>
        <h4>Add new ingredient</h4>
      <%end%>
    <% end %>
  </div>
  <table class="width-100">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @recipe_foods.empty? %>
        <td colspan="4">The food list is empty</td>
      <% else %>
        <% @recipe_foods.each do |recipe_food| %>
          <tr>    
            <td><%= recipe_food.food.name %></td>
            <td><%= recipe_food.quantity %></td>
            <td><%= recipe_food.food.price %></td>
            <td>
              <% if can? :update, recipe_food.recipe %>
                <%=link_to "Modify", edit_recipe_recipe_food_path(@recipe, recipe_food) %>
              <% end %>
              <% if can? :destroy, recipe_food.recipe %>
                <%= link_to "Remove", recipe_recipe_food_path(recipe_food.recipe_id, recipe_food.food_id), data: { turbo_method: :delete } %>
              <% end %>
            </td>
          </tr>
        <%end%>
      <% end %>
    </tbody>
  </table>
  <p></p>
</div>